apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: "gcr.io/cloudorbit/redis:1"
        imagePullPolicy: IfNotPresent
        resources:
          requests: 
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: REDISHOSTIP
          valueFrom:
            configMapKeyRef:
              name: ms-cm
              key: REDISHOSTIP
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
